beds/urls.py
from django.conf.urls import url
from . import views
from django.urls import path
from django.contrib.auth import views as auth_views

app_name = 'beds'

urlpatterns = [
        path('bed_list', views.bed_list, name='bed_list'),
        path('bed/create/', views.bed_new, name='bed_new'),
        path('bed/<int:pk>/edit/', views.bed_edit, name='bed_edit'),
        path('bed/<int:pk>/delete/', views.bed_delete, name='bed_delete'),
	    path('bed_availability',views.bed_availability, name='bed_availability'),
	    path('home/bed_availability',views.bed_availability, name='bed_availability'),
        path('bed_summary_pdf', views.bed_summary_pdf, name='bed_summary_pdf'),
]

chsbeds/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path, re_path, reverse
from django.contrib.auth.views import LoginView, LogoutView
from events import urls, views as event_views
from beds import urls
from patients import urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('events/', include('events.urls')),
    re_path(r'^accounts/login/$', LoginView.as_view(template_name='registration/login.html'), name="login"),
    re_path(r'^accounts/logout/$', LogoutView.as_view(), LogoutView.next_page, name="logout"),
    path('patients/', include('patients.urls')),
    path('beds/', include('beds.urls')),
    path('', event_views.home, name='home'),
    url(r'^home/$', event_views.home, name='home'),
    path('', include('django.contrib.auth.urls'))

]

events/urls.py
from . import views
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, re_path, reverse
from django.contrib.auth import views as auth_views
from beds import urls
from patients import urls


app_name = 'events'

urlpatterns = [

    #Site home pages
    path('', views.home, name='home'),
    url(r'^home/$', views.home, name='home'),

    #Login pages
    url(r'^admin_login/', views.admin_home, name='adminlogin'),
    url(r'^nurse_login/', views.nurse_home, name='nurselogin'),

    #Speecific Admin/User Home Pages
    path('admin_home', views.admin_home, name='admin_home'),
    path('nurse_home', views.nurse_home, name='nurse_home'),

    #change password urls
    path('accounts/password_change/',auth_views.PasswordChangeView.as_view(),name='password_change'),
    path('accounts/password_change/done/',auth_views.PasswordChangeDoneView.as_view(),name='password_change_done'),
    path('password_reset/',	auth_views.PasswordResetView.as_view(),	name='password_reset'),
    path('password_reset/done/',auth_views.PasswordResetDoneView.as_view(),	name='password_reset_done'),
    path('reset/<uidb64>/<token>/',	auth_views.PasswordResetConfirmView.as_view(),name='password_reset_confirm'),
    path('reset/done/',	auth_views.PasswordResetCompleteView.as_view(),	name='password_reset_complete'),

    # Other app url links
    path('patients/', include('patients.urls')),
    path('beds/', include('beds.urls')),

    #Admin usert type selection
    path('admin/user_option', views.user_option, name='user_option'),

    #list pages
    path('admin/users_list', views.users_list, name='users_list'),
    path('admin/nurse_list', views.nurse_list, name='nurse_list'),
    path('event_list', views.event_list, name='event_list'),
    path('org_list', views.org_list, name='org_list'),

    #edit  pages
    path('user/<int:pk>/edit/', views.user_edit, name='user_edit'),
    path('nurse/<int:pk>/edit/', views.nurse_edit, name='nurse_edit'),
    path('event/<int:pk>/edit/', views.event_edit, name='event_edit'),
    path('event/end_curr', views.end_curr_event, name='end_curr_event'),
    path('nurse/force_nurse_pw_reset/', views.force_nurse_pw_reset, name='force_nurse_pw_reset'),
    path('org/<int:pk>/edit/', views.org_edit, name='org_edit'),

    #create pages
    path('user/create/', views.user_new, name='user_new'),
    path('event/create/', views.event_new, name='event_new'),
    path('event/create/notify', views.event_new_notify, name='event_new_notify'),
    path('org/create/', views.org_new, name='org_new'),

    #delete pages
    path('user/<username>/delete/', views.user_delete, name='user_delete'),
    path('event/<int:pk>/delete/', views.event_delete, name='event_delete'),
    path('org_summary_pdf', views.org_summary_pdf, name='org_summary_pdf'),
    path('nurse_summary_pdf', views.nurse_summary_pdf, name='nurse_summary_pdf'),

]

patients/urls.py
from django.conf.urls import url
from . import views
from django.urls import path, re_path, reverse

app_name = 'patients'

urlpatterns = [
    
    #Patient URLs
    path('patient_list', views.patient_list, name='patient_list'),
    path('patient/<int:pk>/edit/', views.patient_edit, name='patient_edit'),
    path('patient/create/', views.patient_new, name='patient_new'),
    path('patient/<int:pk>/delete/', views.patient_delete, name='patient_delete'),
    path('search/', views.patient_search, name='patient_search'),
    path('search_list/', views.patient_search_list, name='patient_search_list'),

    #Triage URLs
    #path('triage/<int:pk>/triage_list', views.triage_list, name='triage_list'),
    #path('triage/<int:pk>/triage_edit', views.triage_edit, name='triage_edit'),
    #path('triage/<int:pk>/delete/', views.triage_delete, name='triage_delete'),
    #path('triage/create/', views.triage_new, name='triage_new'),
   
    #Injury URLs
    path('injury/<int:pk>/injury_list', views.injury_list, name='injury_list'),
    path('injury/<int:pk>/injury_edit', views.injury_edit, name='injury_edit'),
    path('injury/create/', views.injury_new, name='injury_new'),
    path('injury/<int:pk>/delete/', views.injury_delete, name='injury_delete'),

    #Disposition URLs
    path('disposition/<int:pk>/disposition_list', views.disposition_list, name='disposition_list'),
    path('disposition/create/', views.disposition_new, name='disposition_new'),
    path('disposition/<int:pk>/delete/', views.disposition_delete, name='disposition_delete'),
    path('disposition/<int:pk>/disposition_edit', views.disposition_edit, name='disposition_edit'),

]

events/forms.py
from .models import *
from django import forms
from django.contrib.auth.models import User


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'username')

class NurseEditForm(forms.ModelForm):
    class Meta:
        model = Nurse
        fields = ('user','org', 'title', 'phone', 'end_date')

class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = ('event_type', 'event_description', 'event_start_date', 'event_end_date', 'simulation_flag')

class OrgEditForm(forms.ModelForm):
    class Meta:
        model = Organization
        fields = ('org_type', 'org_name', 'org_addr1', 'org_addr2', 'org_city', 'org_state', 'org_zip', 'org_primary_phone')

events/views.py
from .forms import *
from .models import *
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
from django.utils import timezone
from django.contrib.auth.decorators import permission_required
from django.shortcuts import render, get_object_or_404
from .utils import render_to_pdf
from django.template.loader import get_template
from django.template.loader import render_to_string
from django.db.models import Count
from django.contrib.auth.models import Group
from django.utils.crypto import get_random_string
from django.contrib.auth.forms import SetPasswordForm, PasswordResetForm
from django.http import HttpRequest


nurse_group = Group.objects.get(name='Nurse')

# Create your views here.

def getActiveEvent():
    activeEvent = Event.objects.filter(event_end_date__isnull=True)
    return activeEvent



def home(request):

    if getActiveEvent():
        return render(request, 'events/home.html',
                      {'events': home})
    else:
        return render(request, 'events/home_no_event.html',
                      {'events': home})

def adminlogin(request):

    if getActiveEvent():
        if request.user.is_staff:
            return redirect('events/nurse_home.html')
        else:
            return redirect('events/admin_home.html')
    else:
        return render(request, 'events/home_no_event.html',
                      {'events': home})

@permission_required('is_superuser')
def admin_home(request):

    if getActiveEvent():
        return render(request, 'events/admin_home.html',
                      {'admin': admin_home})
    else:
        return render(request, 'events/home_no_event.html',
                      {'events': home})


@permission_required('is_staff')
def admin_home(request):

    return render(request, 'events/admin_home.html',
                  {'chs': admin_home})

def admin_login(request):
        return render(request, 'events/admin_login.html', {'events': admin_login})

@login_required
def nurse_home(request):

    if getActiveEvent():
        return render(request, 'events/nurse_home.html',
                      {'nurse': nurse_home})
    else:
        return render(request, 'events/home_no_event.html',
                      {'events': home})


@login_required
def users_list(request):
    users = User.objects.all()
    #print(users)
    return render(request, 'events/users_list.html', {'users': users})

@login_required
def user_option(request):
    return render(request, 'events/user_option.html',
                 {'admin': user_option})

@login_required
def nurse_list(request):
    #users = User.objects.filter(groups=1)
    nurses = Nurse.objects.filter(end_date__isnull=True)
    return render(request, 'events/nurse_list.html',{'nurses': nurses})


@login_required
def nurse_edit(request, pk):
   user = User.objects.filter(pk=pk).first()
   org = Organization.objects.filter(org_name='Unassigned').first()
   if not org: #check to ensure Unassigned org exists and create if needed
       print("Unassigned org not Found - Creating it")
       # create new nurse thru form
       neworg = Organization.objects.create(org_type='Default',org_name='Unassigned', created_date = timezone.now(), updated_date = timezone.now())
       neworg.save()
       org = Organization.objects.filter(org_name='Unassigned').first()

   #print('USER ' + str(user.pk))
   #print('ORG ' + str(org.pk))
   nurse = Nurse.objects.filter(user_id=user.pk).first()

   if not nurse:
       print("Nurse not Found - Create New")
       # create new nurse thru form
       newNurse = Nurse.objects.create(user=user,org=org)
       newNurse.save()
       form = NurseEditForm(instance=newNurse)
       return render(request, 'events/nurse_edit.html', {'form': form})
   else: #nurse already exists
       print('Nurse ' + str(nurse.user))
       if request.method == "POST":
           # update
           form = NurseEditForm(request.POST, instance=nurse)
           if form.is_valid():
               nurse = form.save(commit=False)
               nurse.updated_date = timezone.now()
               nurse.save()
               nurses = Nurse.objects.all() #filter(end_date__isnull=True)
               return render(request, 'events/nurse_list.html',
                             {'nurses': nurses})
       else:
           # edit
           form = NurseEditForm(instance=nurse)
           return render(request, 'events/nurse_edit.html', {'form': form})

def split_domain_port(host):
    """
    Return a (domain, port) tuple from a given host.

    Returned domain is lowercased. If the host is invalid, the domain will be
    empty.
    """
    host = host.lower()

    if host[-1] == ']':
        # It's an IPv6 address without a port.
        return host, ''
    bits = host.rsplit(':', 1)
    domain, port = bits if len(bits) == 2 else (bits[0], '')
    # Remove a trailing dot (if present) from the domain.
    domain = domain[:-1] if domain.endswith('.') else domain
    if port=='': port = '80'
    return domain, port

def reset_user_pw(request, email):
    # ADD PW RESET CALL HERE
    baseurl = request.get_host()
    print('baseurl: ' + baseurl)
    domain, port = split_domain_port(baseurl)
    print('domain: ' + domain + ' port: ' + port)
    form = PasswordResetForm({'email': email})
    if form.is_valid():
        request = HttpRequest()
        request.META['SERVER_NAME'] = domain
        request.META['SERVER_PORT'] = port
        form.save(
            request=request,
            use_https=False,
            from_email="admin@dcehs.org",
            email_template_name='events/force_pw_reset_notify.html')
        

@login_required
def force_nurse_pw_reset(request):
    #users = User.objects.filter(groups=1)
    nurses = Nurse.objects.filter(end_date__isnull=True)
    for nurse in nurses.iterator():
        print('pk: ' + str(nurse.pk))
        user = get_object_or_404(User, pk=nurse.pk)
        print('email: ' + str(user.email))
        reset_user_pw(request, user.email)
    updated_nurses = Nurse.objects.filter(end_date__isnull=True)
    return render(request, 'events/nurse_list.html',{'nurses': updated_nurses})


@login_required
def user_edit(request, pk):
   user = get_object_or_404(User, pk=pk)
   if request.method == "POST":
       # update
       form = UserEditForm(request.POST, instance=user)
       if form.is_valid():
           user = form.save(commit=False)
           user.updated_date = timezone.now()
           user.save()
           users = User.objects.filter()
           #print(users)
           return render(request, 'events/users_list.html',
                         {'users': users})
   else:
        # edit
       form = UserEditForm(instance=user)
       return render(request, 'events/user_edit.html', {'form': form})

@login_required
def user_delete(request, username):
    users = User.objects.get(username=username)
    users.delete()
    return redirect('events:users_list')


def new_user_pw(request, email):
    # ADD PW RESET CALL HERE
    baseurl = request.get_host()
    print('baseurl: ' + baseurl)
    domain, port = split_domain_port(baseurl)
    print('domain: ' + domain + ' port: ' + port)
    form = PasswordResetForm({'email': email})
    if form.is_valid():
        request = HttpRequest()
        request.META['SERVER_NAME'] = domain
        request.META['SERVER_PORT'] = port
        form.save(
            request=request,
            use_https=False,
            from_email="admin@dcehs.org",
            email_template_name='events/user_new_notify.html')


@login_required
def user_new(request):
    if request.method == "POST":
        form = UserEditForm(request.POST)
        if form.is_valid():
            newuser = form.save(commit=False)
            newuser.date_joined = timezone.now()
            #SET NEW USER PW
            pw = get_random_string()
            print('randPw: ' + pw)
            newuser.set_password(pw)
            #newuser.password1 = pw
            #newuser.password2 = pw
            newuser.save()
            nurse_group.user_set.add(newuser.pk)
            newuser.save()
            new_user_pw(request,newuser.email)
            # user = User.objects.filter(pk=newuser.pk)
            users = User.objects.filter(date_joined__lte=timezone.now())
            return render(request, 'events/users_list.html',
                          {'users': users})
    else:
        form = UserEditForm()
        # print("Else")
    return render(request, 'events/user_new.html', {'form': form})


def event_list(request):
    events = Event.objects.filter(created_date__lte=timezone.now())
    return render(request, 'events/event_list.html',
                 {'events': events})

def event_new(request):
   if request.method == "POST":
       form = EventForm(request.POST)
       if form.is_valid():
           #print("getting active event queryset")
           active_event = getActiveEvent()
           if active_event:
             #print("An Active event already exists - returning to events page")
             return render(request, 'events/event_new_error.html')
           else:
             event = form.save(commit=False)
             event.created_date = timezone.now()
             event.save()
             event_new_notify(request)
             events = Event.objects.filter(created_date__lte=timezone.now())
             return render(request, 'events/event_list.html',
                           {'events': events})
   else:
       form = EventForm()
       # print("Else")
       return render(request, 'events/event_new.html', {'form': form})


def send_new_event_notify(request, email):
    # ADD PW RESET CALL HERE
    baseurl = request.get_host()
    print('baseurl: ' + baseurl)
    domain, port = split_domain_port(baseurl)
    print('domain: ' + domain + ' port: ' + port)
    form = PasswordResetForm({'email': email})
    if form.is_valid():
        request = HttpRequest()

events/templates/events/admin_base.html
{% load staticfiles %}

<html lang="en">
<head>

    <title>Douglas County Emergency Services</title>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <style>
        /* Remove the navbar's default margin-bottom and rounded borders */
        .navbar {
            margin-bottom: 0;
            border-radius: 0;
        }
        /* Set height of the grid so .sidenav can be 100% (adjust as needed) */
        .row.content {
            height: 450px
        }

        /* Set gray background color and 100% height */
        .sidenav {
            padding-top: 20px;
            background-color: #f1f1f1;
            height: 100%;
        }
        /* Set black background color, white text and some padding */
        footer {
            background-color: #555;
            color: white;
            padding: 15px;
        }
        /* On small screens, set height to 'auto' for sidenav and grid */
        @media screen and (max-width: 767px) {
            .sidenav {
                height: auto;
                padding: 15px;
            }
            .row.content {
                height: auto;
            }
        }
    </style>
</head>
<body id="app-layout" class="body" background="{% static 'images/background.jpg' %}" style="height: 100%;
  background-repeat: no-repeat;background-size: cover;">
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
            <img src="{% static 'images/bed.jpg' %}" width="100" height="70" alt="logo"/>

            <a class="navbar-brand" href="{% url 'events:home' %}" style="float: right">Douglas County Emergency Services</a>

        </div>
        <div class="collapse navbar-collapse" id="myNavbar" style="float: right;">
            <ul class="nav navbar-nav">

                {% if user.is_authenticated %}

                    <li><a href="{% url 'events:admin_home' %}">Admin</a></li>
                    <li><a href="{% url 'events:user_option' %}">Manage Users </a></li>
                    <li><a href="{% url 'events:event_list' %}">Manage Events </a></li>
                    <li><a href="{% url 'events:org_list' %}">Manage Organizations </a></li>
                {% endif %}


            </ul>

            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}

                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                           More options <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="{% url 'logout' %}"><i class="fa fa-btn fa-sign-out"></i>Logout</a></li>

                            <li><a href="{% url 'events:password_change'%}"><i class="fa fa-btn fa-sign-out"></i>Change Password</a></li>

                        </ul>
                    </li>
                {% else %}
                    <li><a href="{% url 'login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                {% endif %}
            </ul>
        </div>

    </div>
</nav>

<div class="content container">
    <div class="row">
        <div class="col-md-10">
            {% block content %}
            {% endblock %}
            </div>
        </div>


</div>
</body>
</html>

events/templates/events/admin_event_list.html
{% extends 'events/admin_base.html' %}
{% load staticfiles %}
{% block content %}

    <style>
        body {
            background-color: beige;
        }
        table{
            background-color: azure;
        }
    </style>
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel-primary">
                    <div class="panel-heading">Welcome!</div>
                    <div class="panel-body">
                        Douglas County Emergency Services!.
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <h2 style="padding-left: 15Px">Event Information</h2>
    </div>
    <div>
        <table class="table table-bordered table-hover">
            <thead>
            <tr class="bg-info">
                <th>Event Type</th>
                <th>Event Description</th>

                <th colspan="2">Actions</th>

            </tr>
            </thead>
            <tbody>
            {% for event in event %}
                <tr>
                    <td>{{ event.event_type }}</td>
                    <td>{{ event.event_description }}</td>


                    <td><a href="{% url 'events:event_edit' pk=event.pk %}" class="btn btn-primary">Edit</a></td>
                    <td><a href="{% url 'events:event_delete' pk=event.pk %}" onclick="return confirm('Are you sure you want to delete?')" class="btn btn-primary">Delete</a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

    </div>
{% endblock %}

events/templates/events/admin_home.html
{% extends 'events/admin_base.html' %}
{% load staticfiles %}
{% block content %}

    {% if user.is_authenticated %}
        <div class="page-container">
            <h2 class="top-menu">Welcome {{ user.username }},</h2>
            <p>Please choose from below options.</p>
        </div>
    {% endif %}


    <table>
        <tr><td><p>Manage:</p></td></tr>
        <tr>
            <td><a href="{% url 'events:user_option' %}" ><span class="btn btn-primary">Manage Users</span></a>
                <a href="{% url 'events:event_list' %}" ><span class="btn btn-primary">Manage Events</span></a>
                <a href="{% url 'events:org_list' %}" ><span class="btn btn-primary">Manage Organizations</span></a>
            </td>
        </tr>
        <tr><td><p></p></td></tr>
        <tr><td><p>Reports:</p></td></tr>
        <tr>
            <td><a href="{% url 'beds:bed_summary_pdf' %}" ><span class="btn btn-primary">Bed Report</span></a>
                <a href="{% url 'events:org_summary_pdf' %}" ><span class="btn btn-primary">Organization Report</span></a>
                <a href="{% url 'events:nurse_summary_pdf' %}" ><span class="btn btn-primary">Nurse Report</span></a>
            </td>
        </tr>
        <tr><td><p></p></td></tr>
        <tr><td><p>Search:</p></td></tr>
        <tr>
            <td>
                <a href="{% url 'patients:patient_search' %}" ><span class="btn btn-primary">Search Patients</span></a>
            </td>
        </tr>
    </table>


{% endblock %}

events/templates/events/base.html
{% load staticfiles %}

<html lang="en">
<head>
    <title>Douglas Country Emergency Services</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <style>

        /* Remove the navbar's default margin-bottom and rounded borders */
        .navbar {
            margin-bottom: 0;
            border-radius: 0;
        }
        /* Set height of the grid so .sidenav can be 100% (adjust as needed) */
        .row.content {
            height: 450px
        }

        /* Set gray background color and 100% height */
        .sidenav {
            padding-top: 20px;
            background-color: #f1f1f1;
            height: 100%;
        }
        /* Set black background color, white text and some padding */
        footer {
            background-color: #555;
            color: white;
            padding: 15px;
        }
        /* On small screens, set height to 'auto' for sidenav and grid */
        @media screen and (max-width: 767px) {
            .sidenav {
                height: auto;
                padding: 15px;
            }

            .row.content {
                height: auto;
            }
        }
    </style>
</head>
<body id="app-layout" class="body" background="{% static 'images/background.jpg' %}" style="height: 100%;
  background-repeat: no-repeat;background-size: cover;">
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <img src="{% static 'images/bed.jpg' %}" width="100" height="70" alt="logo" />
                <a class="navbar-brand" href="{% url 'events:home' %}" style="float: right">Douglas County Emergency Services</a>
            </div>
            <div class="collapse navbar-collapse" id="myNavbar" style="float: right;">
                <ul class="nav navbar-nav">
                    {% if user.is_authenticated %}
                        {% if user.is_superuser%}
                            <li><a href="{% url 'events:admin_home' %}">Admin</a></li>
                        {% elif user.groups.all.0.name == "Nurse" %}
                            <li><a href="{% url 'events:nurse_home' %}">Nurse</a></li>
                        {% endif %}
                    {% endif %}


                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}

                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                            More options <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="{% url 'logout' %}"><i class="fa fa-btn fa-sign-out"></i>Logout</a></li>
                            <li><a href="{% url 'events:password_change'%}"><i class="fa fa-btn fa-sign-out"></i>Change Password</a></li>
                        </ul>
                    </li>
                    {% else %}
                    <li><a href="{% url 'login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    <div class="content container">
        <div class="row">
            <div class="col-md-10">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </div>
</body>
</html>

events/templates/events/event_new.html
{% extends 'events/base.html' %}

{% block content %}
<h1>Add New Event</h1>
<form method="POST" class="event-form">
    {% csrf_token %}
    <table border="1">
        {{ form }}
    </table>
    <tr><td><p></p></td></tr>
    <tr>
        <td><button type="submit" class="save btn btn-default">Save</button>
            <a href="{% url 'events:event_list' %}" ><span class="btn btn-primary">Cancel</span></a>
        </td>
    </tr>


</form>
{% endblock %}

events/templates/events/event_new_notify.html
A new emergency event has been initiated and you are designated as the coordinator for your hospital.  Please follow the link below to reset your password
and log into the Douglas County Health Systems Emergency Hospital Bed Tracking System and enter the available bed counts for your hospital.
{{ protocol }}://{{ domain }}{% url "events:password_reset_confirm" uidb64=uid token=token %}
Your username, in case you've forgotten: {{ user.get_username }}

events/templates/events/users_list.html
{% extends 'events/admin_base.html' %}
{% load staticfiles %}
{% block content %}

    {% if user.is_authenticated %}
        <style>
        body {
            background-color: beige;
        }
        table{
            background-color: azure;
        }
    </style>
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel-primary">
                    <div class="panel-heading">Welcome!</div>
                    <div class="panel-body">
                        Douglas County Emergency Services!.
                    </div>
                </div>
            </div>
        </div>
    </div>

        <div class="page-container">
            <h2 class="top-menu">All Users</h2>
            <div class="row">
                <h2 style="padding-left: 15Px">User Information</h2>
            </div>
            <div>
                <table class="table table-striped table-bordered table-hover">
                    <thead>
                    <tr class="bg-info">
                        <th>First Name</th>
                        <th>Last Name</th>
                        <th>EmailID</th>
                        <th>Username</th>
                        <th>Group</th>

                        <th colspan="3">Actions</th>
                    </tr>
                    </thead>
                <tbody>
                    {% for users in users %}
                        <tr>
                            <td>{{ users.first_name }}</td>
                            <td>{{ users.last_name }}</td>
                            <td>{{ users.email }}</td>
                            <td>{{ users.username }}</td>
                            <td>{{ users.groups.all.0.name}}</td>
                            <td><a href="{% url 'events:user_edit' pk=users.pk %}" class="btn btn-primary">Edit</a></td>
                            <td>
                                {% if users.groups.all.0.name == "Nurse" %}

                                    <a href="{% url 'events:nurse_edit' pk=users.pk %}" class="btn btn-primary">Update Nurse</a>
                                {% endif %}
                            </td>
                            <td><a href="{% url 'events:user_delete' users.username %}"
                                onclick="return confirm('Are you sure you want to delete?')"
                                class="btn btn-primary">Delete</a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
                </table>

                <div class="row">
                    <a href="{% url 'events:user_new' %}" class="row"><span
                    class="btn btn-primary">Add User</span></a>
                </div>
            </div>

        </div>
    {% endif %}

    </body>
    </html>
{% endblock %}