beds/urls.py
from django.conf.urls import url
from . import views
from django.urls import path
from django.contrib.auth import views as auth_views

app_name = 'beds'

urlpatterns = [
        path('bed_list', views.bed_list, name='bed_list'),
        path('bed/create/', views.bed_new, name='bed_new'),
        path('bed/<int:pk>/edit/', views.bed_edit, name='bed_edit'),
        path('bed/<int:pk>/delete/', views.bed_delete, name='bed_delete'),
	    path('bed_availability',views.bed_availability, name='bed_availability'),
	    path('home/bed_availability',views.bed_availability, name='bed_availability'),
        path('bed_summary_pdf', views.bed_summary_pdf, name='bed_summary_pdf'),
]

chsbeds/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path, re_path, reverse
from django.contrib.auth.views import LoginView, LogoutView
from events import urls, views as event_views
from beds import urls
from patients import urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('events/', include('events.urls')),
    re_path(r'^accounts/login/$', LoginView.as_view(template_name='registration/login.html'), name="login"),
    re_path(r'^accounts/logout/$', LogoutView.as_view(), LogoutView.next_page, name="logout"),
    path('patients/', include('patients.urls')),
    path('beds/', include('beds.urls')),
    path('', event_views.home, name='home'),
    url(r'^home/$', event_views.home, name='home'),
    path('', include('django.contrib.auth.urls'))

]

events/urls.py
from . import views
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, re_path, reverse
from django.contrib.auth import views as auth_views
from beds import urls
from patients import urls


app_name = 'events'

urlpatterns = [

    #Site home pages
    path('', views.home, name='home'),
    url(r'^home/$', views.home, name='home'),

    #Login pages
    url(r'^admin_login/', views.admin_home, name='adminlogin'),
    url(r'^nurse_login/', views.nurse_home, name='nurselogin'),

    #Speecific Admin/User Home Pages
    path('admin_home', views.admin_home, name='admin_home'),
    path('nurse_home', views.nurse_home, name='nurse_home'),

    #change password urls
    path('accounts/password_change/',auth_views.PasswordChangeView.as_view(),name='password_change'),
    path('accounts/password_change/done/',auth_views.PasswordChangeDoneView.as_view(),name='password_change_done'),
    path('password_reset/',	auth_views.PasswordResetView.as_view(),	name='password_reset'),
    path('password_reset/done/',auth_views.PasswordResetDoneView.as_view(),	name='password_reset_done'),
    path('reset/<uidb64>/<token>/',	auth_views.PasswordResetConfirmView.as_view(),name='password_reset_confirm'),
    path('reset/done/',	auth_views.PasswordResetCompleteView.as_view(),	name='password_reset_complete'),

    # Other app url links
    path('patients/', include('patients.urls')),
    path('beds/', include('beds.urls')),

    #Admin usert type selection
    path('admin/user_option', views.user_option, name='user_option'),

    #list pages
    path('admin/users_list', views.users_list, name='users_list'),
    path('admin/nurse_list', views.nurse_list, name='nurse_list'),
    path('event_list', views.event_list, name='event_list'),
    path('org_list', views.org_list, name='org_list'),

    #edit  pages
    path('user/<int:pk>/edit/', views.user_edit, name='user_edit'),
    path('nurse/<int:pk>/edit/', views.nurse_edit, name='nurse_edit'),
    path('event/<int:pk>/edit/', views.event_edit, name='event_edit'),
    path('event/end_curr', views.end_curr_event, name='end_curr_event'),
    path('nurse/force_nurse_pw_reset/', views.force_nurse_pw_reset, name='force_nurse_pw_reset'),
    path('org/<int:pk>/edit/', views.org_edit, name='org_edit'),

    #create pages
    path('user/create/', views.user_new, name='user_new'),
    path('event/create/', views.event_new, name='event_new'),
    path('event/create/notify', views.event_new_notify, name='event_new_notify'),
    path('org/create/', views.org_new, name='org_new'),

    #delete pages
    path('user/<username>/delete/', views.user_delete, name='user_delete'),
    path('event/<int:pk>/delete/', views.event_delete, name='event_delete'),
    path('org_summary_pdf', views.org_summary_pdf, name='org_summary_pdf'),
    path('nurse_summary_pdf', views.nurse_summary_pdf, name='nurse_summary_pdf'),

]

beds/models.py
from django.utils import timezone
from django.contrib import admin
from django.db import models
from django import forms
from events.models import Event, Organization


class Bed(models.Model):
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    organization = models.ForeignKey(Organization, on_delete=models.CASCADE)
    bed_type = models.CharField(max_length=50, blank=True)
    initial_num = models.IntegerField(blank=True, null=True)
    num_used = models.IntegerField(blank=True, null=True)
    num_available = models.IntegerField(blank=True, null=True)
    created_date = models.DateTimeField(default=timezone.now)
    updated_date = models.DateTimeField(auto_now_add=True)

    def created(self):
        self.created_date = timezone.now()
        self.save()

    def updated(self):
        self.updated_date = timezone.now()
        self.save()

    def __str__(self):
        return str(self.bed_type + ' | ' + self.organization.org_name)

beds/forms.py
from django import forms
from .models import Bed

class BedForm(forms.ModelForm):
    class Meta:
        model = Bed
        fields = ('bed_type', 'initial_num', 'num_used')

beds/views.py
from django.shortcuts import render
from .models import *
from .forms import *
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from django.contrib.auth.decorators import permission_required
from django.shortcuts import get_object_or_404
from django.template.loader import render_to_string
from .utils import render_to_pdf
from django.template.loader import get_template
from events import views as event_views
from events import models as event_models
from patients import models as patient_models
from django.contrib.auth.models import User

def bed_list(request):
    event = event_views.getActiveEvent()
    event_id = event.first().id
    if event_id:
        print('Event: ' + str(event_id))
        user = request.user
        if user.is_authenticated:
            if user.is_superuser:
                bed = Bed.objects.filter(event=event_id)
                return render(request, 'beds/bed_list.html',
                              {'beds': bed})
            else:
                current_user = request.user.id
                curr_username = request.user
                print('current_user_id: ' + str(current_user))
                print('current_user: ' + str(curr_username))
                user = User.objects.filter(id=current_user)
                if user:
                    print('user: ' + str(user))
                    nurse = event_models.Nurse.objects.filter(user_id=current_user).first()
                    if nurse:
                        org_id = nurse.org.id
                        if org_id:
                            print('Found org: ' + str(org_id))
                            bed = Bed.objects.filter(organization=org_id).filter(event=event_id)
                            return render(request, 'beds/bed_list.html',
                                         {'beds': bed})
        else:
            bed = Bed.objects.filter(event=event_id)
            return render(request, 'beds/bed_list.html',
                          {'beds': bed})

def bed_availability(request):
    event = event_views.getActiveEvent()
    event_id = event.first().id
    if event_id:
        print('Event: ' + str(event))
        beds = Bed.objects.filter(event_id=event_id).order_by('organization_id')
        return render(request, 'beds/bed_availability.html', {'beds': beds})

def bed_new(request):
   if request.method == "POST":
       form = BedForm(request.POST)
       if form.is_valid():
           bed = form.save(commit=False)
           activeEvent = event_views.getActiveEvent()
           event_id = activeEvent[0].pk
           print(activeEvent[0].pk)
           current_user = request.user.id
           curr_username = request.user
           print('current_user_id: ' + str(current_user))
           print('current_user: ' + str(curr_username))
           user = User.objects.filter(id=current_user)
           if user:
               print('user: ' + str(user))
               nurse = event_models.Nurse.objects.filter(user_id=current_user).first()
               if nurse:
                   org_id = nurse.org.id
                   if org_id:
                       print('Found org: ' + str(org_id))
                       bed.event_id = activeEvent[0].pk
                       bed.organization_id = org_id
                       bed.num_available = bed.initial_num - bed.num_used
                       bed.created_date = timezone.now()
                       bed.save()
                       beds = Bed.objects.filter(organization=org_id).filter(event=event_id)
                       return render(request, 'beds/bed_list.html',
                                     {'beds': beds})
   else:
       form = BedForm()
       # print("Else")
   return render(request, 'beds/bed_new.html', {'form': form})

def bed_edit(request, pk):
   bed = get_object_or_404(Bed, pk=pk)
   if request.method == "POST":
       # update
       form = BedForm(request.POST, instance=bed)
       if form.is_valid():
           bed = form.save(commit=False)
           bed.num_available = bed.initial_num - bed.num_used
           bed.updated_date = timezone.now()
           bed.save()
           activeEvent = event_views.getActiveEvent()
           event_id = activeEvent[0].pk
           print(activeEvent[0].pk)
           current_user = request.user.id
           curr_username = request.user
           print('current_user_id: ' + str(current_user))
           print('current_user: ' + str(curr_username))
           nurse = event_models.Nurse.objects.filter(user_id=current_user).first()
           if nurse:
               org_id = nurse.org.id
               if org_id:
                   print('Found org: ' + str(org_id))
                   beds = Bed.objects.filter(organization=org_id).filter(event=event_id)
                   return render(request, 'beds/bed_list.html',
                                 {'beds': beds})

   else:
       # edit
       form = BedForm(instance=bed)
       return render(request, 'beds/bed_edit.html', {'form': form})

def bed_delete(request, pk):
   bed = get_object_or_404(Bed, pk=pk)
   bed.delete()
   return redirect('beds:bed_list')

@login_required
def bed_summary_pdf(request):
	beds = Bed.objects.order_by('organization_id')
	context = {'beds': beds,}
	template = get_template('beds/bed_summary_pdf.html')
	html = template.render(context)
	pdf = render_to_pdf('beds/bed_summary_pdf.html', context)

	return pdf

beds/templates/beds/bed_availability.html
{% load static %}
<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="{% static 'css/bed_availability.css' %}">
    <title>Douglas County Emergency Services</title>
</head>
<body>
    <div class="row">
        <h2 align="center">Hospital Bed Information</h2>
    </div>
    <div>
        <table class="blueTable">
            <thead>
                <tr>
                    <th>Hospital Name</th>
                    <th>Bed Type</th>
                    <th># of Beds</th>
                </tr>
            </thead>
            <tbody>
                {% for bed in beds %}
                <tr>
                    <td>{{ bed.organization }}</td>
                    <td>{{ bed.bed_type }}</td>
                    <td>{{ bed.num_available }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="content container">
        <div class="row" style="width:100%">
            <div class="col-md-12" style="width: 100%">
                <div class="links">
                    <div class="row">
                        <div class="col-md-3">
                            <div class="thumbnail">
                                <a href="{% url 'beds:bed_availability' %}"><img src="{% static 'images/bed.jpg' %}" align="left" width="70" height="50" title = "Refresh" alt="Refresh"/></a>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="thumbnail">
                                <a href="{% url 'events:home' %}"><img src="{% static 'images/home1.jpg' %}" align="right" width="100" height="50" title="Home" alt="Home"/></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

beds/templates/beds/bed_delete.html
{% extends 'events/nurse_base.html' %}
 {% block body_block %}
<h1>Delete {{ bed.type }}?</h1>

<form method="post">
    {% csrf_token %}
    <input type="submit" class="btn btn-danger" value="Delete">
    <a href="{% url 'chsbeds:home' pk=bed.id %} ">Cancel</a>

</form>

{% endblock %}

beds/templates/beds/bed_edit.html
{% extends 'events/nurse_base.html' %}
{% block content %}
<h1>Edit Bed Type</h1>

<form method="POST" class="bed-form">
    {% csrf_token %}
    <table border="1">
        {{ form }}
    </table>
    <tr><td><P></P></td></tr>
    <tr>
        <td><button type="submit" class="save btn btn-default">Update</button>
            <a href="{% url 'beds:bed_list' %}" ><span class="btn btn-primary">Cancel</span></a>
        </td>
    </tr>
</form>
{% endblock %}

beds/templates/beds/bed_list.html
{% extends 'events/nurse_base.html' %}
{% block content %}

<html>
<head>
    <meta charset="UTF-8">
    <title>Douglas County Health Services</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

</head>
<body>
    <style>
        body {
            background-color: white;
        }
    </style>
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel-primary">
                    <div class="panel-heading"></div>
                    <div class="panel-body">
                        Douglas County Health Services
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <h2 style="padding-left: 15Px">Bed List</h2>
    </div>
    <div>
        <table class="table table-striped table-bordered table-hover">
            <thead>
                <tr class="bg-info">
                    <th>Event</th>
                    <th>Organization</th>
                    <th>Type</th>
                    <th>Initial Number</th>
                    <th>In Use</th>
                    <th>Available</th>

            <th colspan="5">Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for bed in beds %}
                <tr>
                    <td>{{ bed.event }}</td>
                    <td>{{ bed.organization }}</td>
                    <td>{{ bed.bed_type }}</td>
                    <td>{{ bed.initial_num }}</td>
                    <td>{{ bed.num_used }}</td>
                    <td>{{ bed.num_available }}</td>


                    <td>
                        <a href="{% url 'beds:bed_edit' pk=bed.pk %}" class="btn btn-warning">Edit</a>
                    
                    <td>
                        <a href="{% url 'beds:bed_delete' pk=bed.pk %}"
                           onclick="return confirm('Are you sure you want to delete?')"
                           class="btn btn-danger">Delete</a>
                    </td>
                </tr>

            
                {% endfor %}
                </tbody>
        </table>
        <div class="row">
                <a href="{% url 'beds:bed_new' %}" class="row">
                    <span class="btn btn-primary">Add Beds</span>
                </a>
        </div>
    </div>
</body>
</html>
{% endblock %}

beds/templates/beds/bed_new.html
{% extends 'events/nurse_base.html' %}

{% block content %}
<h1>Add Beds Available</h1>
<form method="POST" class="bed-form">
    {% csrf_token %}
    <table border="1">
        {{ form }}
    </table>
    <tr><td><P></P></td></tr>
    <tr>
        <td><button type="submit" class="save btn btn-default">Save</button>
            <a href="{% url 'beds:bed_list' %}" ><span class="btn btn-primary">Cancel</span></a>
        </td>
    </tr>
</form>
{% endblock %}

beds/templates/beds/bed_summary_pdf.html
{% block content %}

<html>
<head>
    <meta charset="UTF-8">
    <title>Douglas County Health Services</title>

</head>
<body>
    <style>
        body {
            background-color: white;
        }
    </style>
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel-primary">
                    <div class="panel-heading"></div>
                    <div class="panel-body">
                        <strong>Douglas County Health Services</strong>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <h2 style="padding-left: 15Px">Bed List For Current Event</h2>
    </div>
    <div>
        <table class="table table-striped table-bordered table-hover">
            <thead>
                <tr class="bg-info">
                    <td style="text-align:center;background-color:#c7ebff;border:1px solid #060606; padding: 5px"><strong>Event</strong></td>
                    <td style="text-align:center;background-color:#c7ebff;border:1px solid #060606;"><strong>Organization</strong></td>
                    <td style="text-align:center;background-color:#c7ebff;border:1px solid #060606;"><strong>Type</strong></td>
                    <td style="text-align:center;background-color:#c7ebff;border:1px solid #060606;"><strong>Initial Number</strong></td>
                    <td style="text-align:center;background-color:#c7ebff;border:1px solid #060606;"><strong>In Use</strong></td>
                    <td style="text-align:center;background-color:#c7ebff;border:1px solid #060606;"><strong>Available</strong></td>
                </tr>
            </thead>
            <tbody>
                {% for bed in beds %}
                <tr>
                    <td style="text-align:center;background-color:#f0dfdb;border:1px solid #060606; padding: 5px">{{ bed.event }}</td>
                    <td style="text-align:center;background-color:#f0dfdb;border:1px solid #060606;">{{ bed.organization }}</td>
                    <td style="text-align:center;background-color:#f0dfdb;border:1px solid #060606;">{{ bed.bed_type }}</td>
                    <td style="text-align:center;background-color:#f0dfdb;border:1px solid #060606;">{{ bed.initial_num }}</td>
                    <td style="text-align:center;background-color:#f0dfdb;border:1px solid #060606;">{{ bed.num_used }}</td>
                    <td style="text-align:center;background-color:#f0dfdb;border:1px solid #060606;">{{ bed.num_available }}</td>
                </tr>            
                {% endfor %}
                </tbody>
        </table>
    </div>
</body>
</html>
{% endblock %}