beds/urls.py
from django.conf.urls import url
from . import views
from django.urls import path
from django.contrib.auth import views as auth_views

app_name = 'beds'

urlpatterns = [
        path('bed_list', views.bed_list, name='bed_list'),
        path('bed/create/', views.bed_new, name='bed_new'),
        path('bed/<int:pk>/edit/', views.bed_edit, name='bed_edit'),
        path('bed/<int:pk>/delete/', views.bed_delete, name='bed_delete'),
	    path('bed_availability',views.bed_availability, name='bed_availability'),
	    path('home/bed_availability',views.bed_availability, name='bed_availability'),
        path('bed_summary_pdf', views.bed_summary_pdf, name='bed_summary_pdf'),
]

chsbeds/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path, re_path, reverse
from django.contrib.auth.views import LoginView, LogoutView
from events import urls, views as event_views
from beds import urls
from patients import urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('events/', include('events.urls')),
    re_path(r'^accounts/login/$', LoginView.as_view(template_name='registration/login.html'), name="login"),
    re_path(r'^accounts/logout/$', LogoutView.as_view(), LogoutView.next_page, name="logout"),
    path('patients/', include('patients.urls')),
    path('beds/', include('beds.urls')),
    path('', event_views.home, name='home'),
    url(r'^home/$', event_views.home, name='home'),
    path('', include('django.contrib.auth.urls'))

]

events/urls.py
from . import views
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, re_path, reverse
from django.contrib.auth import views as auth_views
from beds import urls
from patients import urls


app_name = 'events'

urlpatterns = [

    #Site home pages
    path('', views.home, name='home'),
    url(r'^home/$', views.home, name='home'),

    #Login pages
    url(r'^admin_login/', views.admin_home, name='adminlogin'),
    url(r'^nurse_login/', views.nurse_home, name='nurselogin'),

    #Speecific Admin/User Home Pages
    path('admin_home', views.admin_home, name='admin_home'),
    path('nurse_home', views.nurse_home, name='nurse_home'),

    #change password urls
    path('accounts/password_change/',auth_views.PasswordChangeView.as_view(),name='password_change'),
    path('accounts/password_change/done/',auth_views.PasswordChangeDoneView.as_view(),name='password_change_done'),
    path('password_reset/',	auth_views.PasswordResetView.as_view(),	name='password_reset'),
    path('password_reset/done/',auth_views.PasswordResetDoneView.as_view(),	name='password_reset_done'),
    path('reset/<uidb64>/<token>/',	auth_views.PasswordResetConfirmView.as_view(),name='password_reset_confirm'),
    path('reset/done/',	auth_views.PasswordResetCompleteView.as_view(),	name='password_reset_complete'),

    # Other app url links
    path('patients/', include('patients.urls')),
    path('beds/', include('beds.urls')),

    #Admin usert type selection
    path('admin/user_option', views.user_option, name='user_option'),

    #list pages
    path('admin/users_list', views.users_list, name='users_list'),
    path('admin/nurse_list', views.nurse_list, name='nurse_list'),
    path('event_list', views.event_list, name='event_list'),
    path('org_list', views.org_list, name='org_list'),

    #edit  pages
    path('user/<int:pk>/edit/', views.user_edit, name='user_edit'),
    path('nurse/<int:pk>/edit/', views.nurse_edit, name='nurse_edit'),
    path('event/<int:pk>/edit/', views.event_edit, name='event_edit'),
    path('event/end_curr', views.end_curr_event, name='end_curr_event'),
    path('nurse/force_nurse_pw_reset/', views.force_nurse_pw_reset, name='force_nurse_pw_reset'),
    path('org/<int:pk>/edit/', views.org_edit, name='org_edit'),

    #create pages
    path('user/create/', views.user_new, name='user_new'),
    path('event/create/', views.event_new, name='event_new'),
    path('event/create/notify', views.event_new_notify, name='event_new_notify'),
    path('org/create/', views.org_new, name='org_new'),

    #delete pages
    path('user/<username>/delete/', views.user_delete, name='user_delete'),
    path('event/<int:pk>/delete/', views.event_delete, name='event_delete'),
    path('org_summary_pdf', views.org_summary_pdf, name='org_summary_pdf'),
    path('nurse_summary_pdf', views.nurse_summary_pdf, name='nurse_summary_pdf'),

]

patients/urls.py
from django.conf.urls import url
from . import views
from django.urls import path, re_path, reverse

app_name = 'patients'

urlpatterns = [
    
    #Patient URLs
    path('patient_list', views.patient_list, name='patient_list'),
    path('patient/<int:pk>/edit/', views.patient_edit, name='patient_edit'),
    path('patient/create/', views.patient_new, name='patient_new'),
    path('patient/<int:pk>/delete/', views.patient_delete, name='patient_delete'),
    path('search/', views.patient_search, name='patient_search'),
    path('search_list/', views.patient_search_list, name='patient_search_list'),

    #Triage URLs
    #path('triage/<int:pk>/triage_list', views.triage_list, name='triage_list'),
    #path('triage/<int:pk>/triage_edit', views.triage_edit, name='triage_edit'),
    #path('triage/<int:pk>/delete/', views.triage_delete, name='triage_delete'),
    #path('triage/create/', views.triage_new, name='triage_new'),
   
    #Injury URLs
    path('injury/<int:pk>/injury_list', views.injury_list, name='injury_list'),
    path('injury/<int:pk>/injury_edit', views.injury_edit, name='injury_edit'),
    path('injury/create/', views.injury_new, name='injury_new'),
    path('injury/<int:pk>/delete/', views.injury_delete, name='injury_delete'),

    #Disposition URLs
    path('disposition/<int:pk>/disposition_list', views.disposition_list, name='disposition_list'),
    path('disposition/create/', views.disposition_new, name='disposition_new'),
    path('disposition/<int:pk>/delete/', views.disposition_delete, name='disposition_delete'),
    path('disposition/<int:pk>/disposition_edit', views.disposition_edit, name='disposition_edit'),

]

patients/forms.py
from django import forms
from .models import *

class PatientForm(forms.ModelForm):
    class Meta:
        model = Patient
        fields = ('patient_last_name', 'patient_first_name', 'patient_middle_name', 'age', 'dob', 'gender', 'unique_characteristics', 'next_of_kin_name', 'next_of_kin_relation', 'next_of_kin_phone', 'triage_tag_num', 'tag_color_condition', 'mode_of_arrival', 'arrival_date', 'arrival_condition', 'room_number', 'created_date')

class PatientTriageForm(forms.ModelForm):
    class Meta:
        model = PatientTriage
        fields = ('patient', 'triage_tag_num', 'tag_color_condition', 'mode_of_arrival', 'arrival_date', 'arrival_condition', 'room_number')

class InjuryForm(forms.ModelForm):
    class Meta:
        model = Injury
        fields = ('patient', 'injury_type', 'created_date')

class DispositionForm(forms.ModelForm):
    class Meta:
        model = Disposition
        fields = ('patient', 'disposition_type', 'description', 'transfer_to_org', 'time_of_death', 'updated_condition', 'created_date')

patients/views.py
from .models import *
from .forms import *
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
from django.utils import timezone
from django.contrib.auth.decorators import permission_required
from django.shortcuts import render, get_object_or_404
from events.views import getActiveEvent
from events.models import Organization, Nurse
from patients.forms import forms as patient_forms
from django.contrib.auth.models import User
from django.http import HttpResponse

# Create your views here.
def patient_list(request):
    # ensure there is an acti99*ve event
    event = getActiveEvent()
    event_id = event.first().id
    if event_id:
       print('Event: ' + str(event_id))
       current_user = request.user.id
       curr_username = request.user
       print('current_user_id: ' + str(current_user))
       print('current_user: ' + str(curr_username))
       user = User.objects.filter(id=current_user)
       if user:
           print('user: ' + str(user))
           nurse = Nurse.objects.filter(user_id=current_user).first()
           if nurse:
               org_id = nurse.org.id
               if org_id:
                   print('Found org: ' + str(org_id))
                   patients=Patient.objects.filter(organization=org_id).filter(event=event_id)
                   for patient in patients:
                       print('Patient: ' + chr(patient.id))                   
                   return render(request, 'patients/patient_list.html',
                                 {'patients': patients})
               else:
                   patients = Patient.object.none()
                   return render(request, 'events/nurse_home.html')
           else:
               patients = Patient.object.none()
               return render(request, 'events/nurse_home.html')
       else:
           patients = Patient.object.none()
           return render(request, 'events/nurse_home.html')
    else:
        patients = Patient.object.none()
        #   patients = Patient.objects.filter(created_date__lte=timezone.now())
        return render(request, 'events/nurse_home.html')

def patient_new(request):
   if request.method == "POST":
       event = getActiveEvent()
       event_id = event.first().id
       # ensure there is an active event
       if event:
           print('Event: ' + str(event))
           current_user = request.user.id
           curr_username = request.user
           print('current_user_id: ' + str(current_user))
           print('current_user: ' + str(curr_username))
           user = User.objects.filter(id=current_user)
           if user:
               print('user: ' + str(user))
               nurse = Nurse.objects.filter(user_id=current_user).first()
               if nurse:
                   org_id = nurse.org.id
                   if org_id:
                       print('Found org: ' + str(org_id))
                   form = PatientForm(request.POST)
                   if form.is_valid():
                       patient = form.save(commit=False)
                       patient.organization_id = org_id
                       patient.event_id = event_id
                       patient.created_date = timezone.now()
                       patient.save()
                       patients = Patient.objects.filter(created_date__lte=timezone.now())
                       return render(request, 'patients/patient_list.html',
                                     {'patients': patients})
   else:
       form = PatientForm()
       # print("Else")
   return render(request, 'patients/patient_new.html', {'form': form})

def patient_edit(request, pk):
   patient = get_object_or_404(Patient, pk=pk)
   if request.method == "POST":
       # update
       form = PatientForm(request.POST, instance=patient)
       if form.is_valid():
           patient = form.save(commit=False)
           patient.updated_date = timezone.now()
           patient.save()
           patient = Patient.objects.filter(created_date__lte=timezone.now())
           return render(request, 'patients/patient_list.html',
                         {'patients': patient})
   else:
        # edit
       form = PatientForm(instance=patient)
   return render(request, 'patients/patient_edit.html', {'form': form})

def patient_delete(request, pk):
   patient = get_object_or_404(Patient, pk=pk)
   patient.delete()
   return redirect('patients:patient_list')

'''
#Patient Summary

#Triage
def triage_list(request, pk):
    patient = get_object_or_404(Patient, pk=pk)
    triage = PatientTriage.objects.filter(patient=patient.pk)
    return render(request, 'patients/triage_list.html',
                 {'triages': triage})

def triage_new(request):
   if request.method == "POST":
       form = PatientTriageForm(request.POST)
       if form.is_valid():
           triage = form.save(commit=False)
           triage.created_date = timezone.now()
           triage.save()
           triages = PatientTriage.objects.filter(created_date__lte=timezone.now())
           return render(request, 'patients/triage_list.html',
                         {'triages': triage})
   else:
       form = PatientTriageForm()
       # print("Else")
   return render(request, 'patients/triage_new.html', {'form': form})

def triage_edit(request, pk):
   triage = get_object_or_404(PatientTriage, pk=pk)
   if request.method == "POST":
       # update
       form = PatientTriageForm(request.POST, instance=triage)
       if form.is_valid():
           triage = form.save(commit=False)
           triage.updated_date = timezone.now()
           triage.save()
           triage = PatientTriage.objects.filter(created_date__lte=timezone.now())
           return render(request, 'patients/triage_list.html',
                         {'triages': triage})
   else:
        # edit
       form = PatientTriageForm(instance=triage)
   return render(request, 'patients/triage_edit.html', {'form': form})

def triage_delete(request, pk):
   triage = get_object_or_404(PatientTriage, pk=pk)
   triage.delete()
   return redirect('patients:patient_list')
'''

#injury
def injury_list(request, pk):
    patient = get_object_or_404(Patient, pk=pk)
    injury = Injury.objects.filter(patient=patient.pk)
    return render(request, 'patients/injury_list.html',
                 {'injuries': injury})

def injury_new(request):
   if request.method == "POST":
       form = InjuryForm(request.POST)
       if form.is_valid():
           injury = form.save(commit=False)
           injury.created_date = timezone.now()
           injury.save()
           patient = Patient.objects.filter(id=injury.patient.id).first()
           injuries = Injury.objects.filter(patient=patient)
           return render(request, 'patients/injury_list.html',
                         {'injuries': injuries})
   else:
       form = InjuryForm()
       # print("Else")
   return render(request, 'patients/injury_new.html', {'form': form})

def injury_edit(request, pk):
   injury = get_object_or_404(Injury, pk=pk)
   if request.method == "POST":
       # update
       form = InjuryForm(request.POST, instance=injury)
       if form.is_valid():
           injury = form.save(commit=False)
           patient=Patient.objects.filter(id=injury.patient.id).first()
           injury.updated_date = timezone.now()
           injury.save()
           injury = Injury.objects.filter(patient=patient)
           return render(request, 'patients/injury_list.html',
                         {'injuries': injury})
   else:
        # edit
       form = InjuryForm(instance=injury)
   return render(request, 'patients/injury_edit.html', {'form': form})

def injury_delete(request, pk):
    injury = get_object_or_404(Injury, pk=pk)
    patient = Patient.objects.filter(id=injury.patient.id).first()
    injury.delete()
    injuries = Injury.objects.filter(patient=patient)
    return render(request, 'patients/injury_list.html',
                  {'injuries': injuries})

#disposition list
def disposition_list(request, pk):
    patient = get_object_or_404(Patient, pk=pk)
    disposition = Disposition.objects.filter(patient=patient.pk)
    return render(request, 'patients/disposition_list.html',
                 {'dispositions': disposition})

def disposition_new(request):
   if request.method == "POST":
       form = DispositionForm(request.POST)
       if form.is_valid():
           disposition = form.save(commit=False)
           disposition.created_date = timezone.now()
           disposition.save()
           patient = Patient.objects.filter(id=disposition.patient.id).first()
           disposition = Disposition.objects.filter(patient=patient)
           return render(request, 'patients/disposition_list.html',
                         {'dispositions': disposition})
   else:
       form = DispositionForm
       # print("Else")
   return render(request, 'patients/disposition_new.html', {'form': form})

def disposition_delete(request, pk):
   disposition = get_object_or_404(Disposition, pk=pk)
   disposition.delete()
   return redirect('patients:patient_list')

def disposition_edit(request, pk):
   disposition = get_object_or_404(Disposition, pk=pk)
   if request.method == "POST":
       # update
       form = DispositionForm(request.POST, instance=disposition)
       if form.is_valid():
           disposition = form.save(commit=False)
           patient = Patient.objects.filter(id=disposition.patient.id).first()
           disposition.updated_date = timezone.now()
           disposition.save()
           disposition = Disposition.objects.filter(patient=patient)
           return render(request, 'patients/disposition_list.html',
                         {'dispositions': disposition})
   else:
        # edit
       form = DispositionForm(instance=disposition)
   return render(request, 'patients/disposition_edit.html', {'form': form})
    
    
def patient_search(request):
    return render(request, 'patients/patient_search.html')

patients/templates/patients/disposition_delete.html
{% extends 'events/nurse_base.html' %}
{% block body_block %}
<h1>Delete</h1>

<form method="post">
    {% csrf_token %}
    <input type="submit" class="btn btn-danger" value="Delete">
    <a href="{% url 'patients:disposition_list' pk=patient.patient.pk %} ">Cancel</a>

</form>

{% endblock %}

patients/templates/patients/disposition_list.html
{% extends 'events/nurse_base.html' %}
{% load staticfiles %}
{% block content %}

<html>
<head>
    <meta charset="UTF-8">
    <title>Douglas County Health Services</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

</head>
<body>
    <style>
        body {
            background-color: white;
        }
    </style>
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel-primary">
                    <div class="panel-heading"></div>
                    <div class="panel-body">
                        Douglas County Health Services
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <h2 style="padding-left: 15Px">Disposition {{triage.patient}}</h2>
    </div>
    <div>
        <table class="table table-striped table-bordered table-hover">
            <thead>
                <tr class="bg-info">
                    <th>Patient</th>
                    <th>Disposition Type</th>
                    <th>Description</th>
                    <th>Transfer to Org</th>
                    <th>Time of Death</th>
                    <th>Updated Condition</th>

                    <th colspan="5">Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for disposition in dispositions %}
                <tr>
                    <td>{{ disposition.patient }}</td>
                    <td>{{ disposition.disposition_type }}</td>
                    <td>{{ disposition.description }}</td>
                    <td>{{ disposition.transfer_to_org }}</td>
                    <td>{{ disposition.time_of_death }}</td>
                    <td>{{ disposition.updated_condition }}</td>

                    <td>
                        <a href="{% url 'patients:disposition_edit' pk=disposition.pk %}" class="btn btn-warning">Edit</a>
                    <td>
                        <a href="{% url 'patients:disposition_delete' pk=disposition.pk %}"
                           onclick="return confirm('Are you sure you want to delete?')"
                           class="btn btn-danger">Delete</a>
                    </td>


                </tr>
                {% endfor %}
            </tbody>
        </table>
        <tr><td><P></P></td></tr>
        <tr>
            <td><a href="{% url 'patients:disposition_new' %}" ><span class="btn btn-primary">Add Disposition</span></a>
                <a href="{% url 'patients:patient_list' %}" ><span class="btn btn-primary">Patient List</span></a>
            </td>
        </tr>
  </div>

</body>
</html>
{% endblock %}

patients/templates/patients/injury_delete.html
{% extends 'events/nurse_base.html' %}
{% block body_block %}
<h1>Delete</h1>

<form method="post">
    {% csrf_token %}
    <input type="submit" class="btn btn-danger" value="Delete">
    <a href="{% url 'patients:injury_list' pk=injury.injury_id %} ">Cancel</a>

</form>

{% endblock %}

patients/templates/patients/injury_list.html
{% extends 'events/nurse_base.html' %}
{% load staticfiles %}
{% block content %}

<html>
<head>
    <meta charset="UTF-8">
    <title>Douglas County Health Services</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

</head>
<body>
    <style>
        body {
            background-color: white;
        }
    </style>
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel-primary">
                    <div class="panel-heading"></div>
                    <div class="panel-body">
                        Douglas County Health Services
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <h2 style="padding-left: 15Px">Injuries {{ injury.patient }}</h2>
    </div>
    <div>
        <table class="table table-striped table-bordered table-hover">
            <thead>
                <tr class="bg-info">
                    <th>Patient</th>
                    <th>Injury</th>
                    <th>Created</th>

                    <th colspan="5">Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for injury in injuries %}
                <tr>
                    <td>{{ injury.patient }}</td>
                    <td>{{ injury.injury_type }}</td>
                    <td>{{ injury.created_date }}</td>

                    <td>
                        <a href="{% url 'patients:injury_edit' pk=injury.pk %}" class="btn btn-warning">Edit</a>
                    <td>
                        <a href="{% url 'patients:injury_delete' pk=injury.pk %}"
                           onclick="return confirm('Are you sure you want to delete?')"
                           class="btn btn-danger">Delete</a>
                    </td>


                </tr>
                {% endfor %}
            </tbody>
        </table>
        <tr><td><P></P></td></tr>
        <tr>
            <td><a href="{% url 'patients:injury_new' %}" ><span class="btn btn-primary">Add Injury</span></a>
                <a href="{% url 'patients:patient_list' %}" ><span class="btn btn-primary">Patient List</span></a>
            </td>
        </tr>
    </div>

</body>
</html>
{% endblock %}

patients/templates/patients/patient_list.html
{% extends 'events/nurse_base.html' %}
{% load staticfiles %}
{% block content %}

<html>
<head>
    <meta charset="UTF-8">
    <title>Douglas County Health Services</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

</head>
<body>
    <style>
        body {
            background-color: white;
        }
    </style>
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel-primary">
                    <div class="panel-heading"></div>
                    <div class="panel-body">
                       Douglas County Health Services
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <h2 style="padding-left: 15Px">Patient List</h2>
    </div>
    <div>
        <table class="table table-striped table-bordered table-hover">
            <thead>
                <tr class="bg-info">
                    <th>Last name</th>
                    <th>First Name</th>
                    <th>M.I.</th>
                    <th>Age</th>
                    <th>D.O.B.</th>
                    <th>Gender</th>
                    <th>Unique Characteristics</th>
                    <th>N.O.K. Name</th>
                    <th>N.O.K. Relation</th>
                    <th>N.O.K. Phone</th>
                    <th>Triage Tag Number</th>
                    <th>Tag Color - Condition</th>
                    <th>Mode of Arrival</th>
                    <th>Arrival Date</th>
                    <th>Arrival Condition</th>
                    <th>Room Number</th>
                    <th>Created Date</th>
                    <th>UpdatedDate</th>
                </tr>
                <tr>
                    <th colspan="5">Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for patient in patients %}
                <tr>
                    <td>{{ patient.patient_last_name }}</td>
                    <td>{{ patient.patient_first_name }}</td>
                    <td>{{ patient.patient_middle_name }}</td>
                    <td>{{ patient.age }}</td>
                    <td>{{ patient.dob }}</td>
                    <td>{{ patient.gender }}</td>
                    <td>{{ patient.unique_characteristics }}</td>
                    <td>{{ patient.next_of_kin_name }}</td>
                    <td>{{ patient.next_of_kin_relation }}</td>
                    <td>{{ patient.next_of_kin_phone }}</td>
                    <td>{{ patient.triage_tag_num }}</td>
                    <td>{{ patient.tag_color_condition }}</td>
                    <td>{{ patient.mode_of_arrival }}</td>
                    <td>{{ patient.arrival_date }}</td>
                    <td>{{ patient.arrival_condition }}</td>
                    <td>{{ patient.room_number }}</td>
                    <td>{{ patient.created_date }}</td>
                    <td>{{ patient.updated_date }}</td>
                </tr>
                <tr>
                    <td>
                        <a href="{% url 'patients:patient_edit' pk=patient.pk %}" class="btn btn-warning">Edit</a>
                    <td>
                        <a href="{% url 'patients:patient_delete' pk=patient.pk %}"
                           onclick="return confirm('Are you sure you want to delete?')"
                           class="btn btn-danger">Delete</a>
                    </td>

                    <td>
                        <a href="{% url 'patients:injury_list' pk=patient.pk %}" class="btn btn-primary">Injury Summary</a>

                    <td>
                        <a href="{% url 'patients:disposition_list' pk=patient.pk %}" class="btn btn-primary">Disposition Summary</a>

                </tr>
                {% endfor %}
            </tbody>
        </table>
        <div class="row">
            <a href="{% url 'patients:patient_new' %}" class="row">
                <span class="btn btn-primary">Add Patient</span>
            </a>
        </div>
    </div>
</body>
</html>
{% endblock %}

patients/templates/patients/patient_search.html
{% extends 'events/base.html' %}
{% block content %}

<h1>Enter name to search for patient</h1>
<body>
    <form action="{% url 'patients:patient_search_list' %}" method="GET">

        <label for="first_name">First Name:</label>
        <input type="text" name="first_name" >
        <label for="last_name">Last Name:</label>
        <input type="text" name="last_name">
        <input type="submit" value="Search">
        {%  comment %}
        <a href="{% url 'patients:patient_search_list' %}" class="row"><span class="btn btn-primary">Search Patients</span></a>
        {%  endcomment %}
    </form>
</body>
{% endblock %}

patients/templates/patients/patient_search_list.html
{% extends 'events/base.html' %}
{% load staticfiles %}
{% block content %}

<html>
<head>
    <meta charset="UTF-8">
    <title>Douglas County Health Services</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

</head>
<body>
    <style>
        body {
            background-color: white;
        }
    </style>
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel-primary">
                    <div class="panel-heading"></div>
                    <div class="panel-body">
                       Douglas County Health Services
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <h2 style="padding-left: 15Px">Patient List</h2>
    </div>
    <div>
        {% if patients %}
            <table class="table table-striped table-bordered table-hover">
                <thead>
                    <tr class="bg-info">
                        <th>Hospital</th>
                        <th>Last name</th>
                        <th>First Name</th>
                        <th>M.I.</th>
                        <th>Age</th>
                        <th>D.O.B.</th>
                        <th>Gender</th>
                        <th>Unique Characteristics</th>
                        <th>N.O.K. Name</th>
                        <th>N.O.K. Relation</th>
                        <th>Triage Tag Number</th>
                        <th>Tag Color - Condition</th>
                        <th>Mode of Arrival</th>
                        <th>Arrival Date</th>
                        <th>Arrival Condition</th>
                        <th>Room Number</th>
                        <th>Created Date</th>
                        <th>UpdatedDate</th>


                        <th colspan="5">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for patient in patients %}
                    <tr>
                        <td>{{ patient.organization }}</td>
                        <td>{{ patient.patient_last_name }}</td>
                        <td>{{ patient.patient_first_name }}</td>
                        <td>{{ patient.patient_middle_name }}</td>
                        <td>{{ patient.age }}</td>
                        <td>{{ patient.dob }}</td>
                        <td>{{ patient.gender }}</td>
                        <td>{{ patient.unique_characteristics }}</td>
                        <td>{{ patient.next_of_kin_name }}</td>
                        <td>{{ patient.next_of_kin_relation }}</td>
                        <td>{{ patient.next_of_kin_phone }}</td>
                        <td>{{ patient.triage_tag_num }}</td>
                        <td>{{ patient.tag_color_condition }}</td>
                        <td>{{ patient.mode_of_arrival }}</td>
                        <td>{{ patient.arrival_date }}</td>
                        <td>{{ patient.arrival_condition }}</td>
                        <td>{{ patient.room_number }}</td>
                        <td>{{ patient.created_date }}</td>
                        <td>{{ patient.updated_date }}</td>
                    {% endfor %}
                </tbody>
            </table>
        {%  else %}
            <p>No Patients found with that name</p>
        {%  endif %}

        <tr><td><P></P></td></tr>
        <tr>
            <td><a href="{% url 'events:home' %}" ><span class="btn btn-primary">Home</span></a>
                <a href="{% url 'patients:patient_search' %}" ><span class="btn btn-primary">Search Again</span></a>
            </td>
        </tr>

    </div>
</body>
</html>
{% endblock %}